theme: minima
title: ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡ ♡
author: by: nono ◡̈
description: imagine if you combined all the love in the world. all that there ever was and ever will be. my love for tiffanie is more than all of that combined and then multiplied by infinity, infinity times. 
